pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'npm i'
            }
        }
    }
        stage('Build') {
            steps {
                dir('/var/jenkins_home/workspace/aws-node/aws-nodejs-eb') {
                    /* execute commands in the scripts directory */
        }
            }
        stage('Deploy') {
            steps {
                sh 'npm start'
            }
        }   
    }
}
